/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 POLE_01.3.gltf 
*/

import React from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

import FakeGlowMaterial from "../../FakeGlowMaterial";
import { Sphere } from "@react-three/drei";
import { map } from "../../utils/utils";

import EnhancedSpotlight from "../../EnhancedSpotlight";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/gltf/Pole/POLE_01.3.gltf");

  const dimmingValue = map(props.dimmingValue, 0, 1, 0, 1);

  return (
    <group {...props} dispose={null}>
      {/* Put lights here */}
      <group position={[3.3, 0.45, -1.58]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={0.5}
          attenuation={dimmingValue}
          distance={5}
          opacity={0.6}
          // angle={0.2}
        />
      </group>
      <group position={[3.02, 0.45, -2.07]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={0.5}
          attenuation={dimmingValue}
          distance={5}
          opacity={0.6}
          // angle={0.2}
        />
      </group>

      <Sphere
        args={[1.5, 32, 32]}
        position={[0.6, 1.55, -0.35]}
        renderOrder={1}
      >
        <FakeGlowMaterial
          falloff={3.5}
          glowInternalRadius={7}
          glowColor={"#fff"}
          glowSharpness={dimmingValue}
          // toneMapped={true}
          depthTest={false}
        />
      </Sphere>

      <group scale={0.001}>
        <group
          position={[2021.836, 7.878, -1107.711]}
          rotation={[-Math.PI / 2, 0, 0.52]}
          scale={0.657}
        >
          <group
            position={[-2336.68, 73.962, 0]}
            rotation={[Math.PI / 2, 1.571, 0]}
          >
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude1(C894CD29-6B4F-4125-9063-411CE31CD065)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["CirPattern1(178A229C-9868-4FEC-8CCB-E1C1319E84AE)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <group
            position={[-2397.18, 73.957, 2516.5]}
            rotation={[Math.PI / 2, -1.571, 0]}
          >
            <mesh
              castShadow
              geometry={
                nodes["Cut-Extrude22(45C9508D-8C03-40D9-BCEE-292D25A90928)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(B2BFC6F6-98EB-44A8-BA8C-0FE13B4222A7)"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(84CAF7E1-14DD-411C-828F-09AB95A6F813)"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(0A7DA5F2-119F-4370-A0B7-9FBC5C93C290)"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(FDF5C64B-3E7E-4D54-8D9C-1729465887BD)"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <group
            position={[-2334.38, 68.922, 2041.67]}
            rotation={[Math.PI / 2, -0.524, 0]}
          >
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid3(2A132EFC-1D7D-4881-A50E-55E18C47581D)"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid4(BDEF34BE-6541-45ED-91EB-866838FB5393)"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid6(F4D663D9-C0BF-411D-A8B2-4AC5798A200B)"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid2(3771A8AB-9AC3-480D-8410-B1E2EBB12196)"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid1(7D257E27-FFA1-43DF-A00B-C0CFC9BC6FB6)"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(13BB321C-CE35-4D0D-A0B9-B3924F22B95A)"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(38EA1C43-736F-40F4-BA23-7F6BE8B5697D)"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <group
            position={[-2342.2, 74.484, 2041.67]}
            rotation={[-Math.PI / 2, -0.524, Math.PI]}
          >
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid3(2A132EFC-1D7D-4881-A50E-55E18C47581D)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid4(BDEF34BE-6541-45ED-91EB-866838FB5393)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid6(F4D663D9-C0BF-411D-A8B2-4AC5798A200B)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid2(3771A8AB-9AC3-480D-8410-B1E2EBB12196)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid1(7D257E27-FFA1-43DF-A00B-C0CFC9BC6FB6)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(13BB321C-CE35-4D0D-A0B9-B3924F22B95A)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(38EA1C43-736F-40F4-BA23-7F6BE8B5697D)_1"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <group
            position={[-2333.47, 78.479, 2041.67]}
            rotation={[Math.PI / 2, 1.571, 0]}
          >
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid3(2A132EFC-1D7D-4881-A50E-55E18C47581D)_2"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid4(BDEF34BE-6541-45ED-91EB-866838FB5393)_2"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid6(F4D663D9-C0BF-411D-A8B2-4AC5798A200B)_2"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid2(3771A8AB-9AC3-480D-8410-B1E2EBB12196)_2"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid1(7D257E27-FFA1-43DF-A00B-C0CFC9BC6FB6)_2"
                ].geometry
              }
              material={materials.Domino}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(13BB321C-CE35-4D0D-A0B9-B3924F22B95A)_2"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes[
                  "AGO_DOMINO_Pendant_Single_dummy-1-solid5(38EA1C43-736F-40F4-BA23-7F6BE8B5697D)_2"
                ].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <group
            position={[-2276.18, 73.966, 2516.5]}
            rotation={[Math.PI / 2, 1.571, 0]}
          >
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude22(45C9508D-8C03-40D9-BCEE-292D25A90928)_1"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(B2BFC6F6-98EB-44A8-BA8C-0FE13B4222A7)_1"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(84CAF7E1-14DD-411C-828F-09AB95A6F813)_1"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(0A7DA5F2-119F-4370-A0B7-9FBC5C93C290)_1"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["NONE(FDF5C64B-3E7E-4D54-8D9C-1729465887BD)_1"].geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
          </group>
          <mesh
            CastShadow
            geometry={
              nodes["Standard(E6975528-2513-4F91-AC66-41C59A3482A1)"].geometry
            }
            material={materials["Hard Textured Plastic Black #1"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(31E407B1-14A5-47C5-AC17-F0444BDA3617)"].geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.69, 97.962, 2060]}
            rotation={[Math.PI / 2, -1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(31E407B1-14A5-47C5-AC17-F0444BDA3617)_1"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 49.962, 145]}
            rotation={[0, 1.299, 1.571]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(A64C728B-7C2C-4E6B-AD98-BE4D580358CB)"].geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2260.96, -159.042, -12]}
            rotation={[0, 0, 1.571]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(A64C728B-7C2C-4E6B-AD98-BE4D580358CB)_1"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2260.99, 306.976, -12]}
            rotation={[0, 0, -2.199]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(31E407B1-14A5-47C5-AC17-F0444BDA3617)_2"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.69, 97.962, 145]}
            rotation={[Math.PI / 2, -1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)"].geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2391.68, 73.958, 2540.5]}
            rotation={[-Math.PI / 2, 1.419, Math.PI / 2]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_1"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2376.69, 143.241, 2270.5]}
            rotation={[-Math.PI / 2, -1.024, Math.PI / 2]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(A64C728B-7C2C-4E6B-AD98-BE4D580358CB)_2"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2534.9, 217.955, -12]}
            rotation={[0, 0, -0.942]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_2"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2281.68, 73.965, 2540.5]}
            rotation={[-Math.PI / 2, 1.459, Math.PI / 2]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_3"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2312.68, 73.963, 2471.5]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude1(1D40EA5E-6A01-438E-A4C3-1D7EA695369F)"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 1910]}
            rotation={[Math.PI / 2, -0.524, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(31E407B1-14A5-47C5-AC17-F0444BDA3617)_3"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 49.962, 2060]}
            rotation={[0, 0.434, 1.571]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude2(C0895128-D99F-47E9-9CB2-E68CFBCFE1EC)"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2405.68, 73.957, 2516.5]}
            rotation={[Math.PI / 2, -1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_4"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2360.68, 73.96, 2471.5]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude1(1D40EA5E-6A01-438E-A4C3-1D7EA695369F)_1"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 1910]}
            rotation={[Math.PI / 2, 1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude1(1D40EA5E-6A01-438E-A4C3-1D7EA695369F)_2"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 1910]}
            rotation={[-Math.PI / 2, -0.524, -Math.PI]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_5"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2376.68, 4.677, 2270.5]}
            rotation={[Math.PI / 2, -0.023, -Math.PI / 2]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(A64C728B-7C2C-4E6B-AD98-BE4D580358CB)_3"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2091.68, 73.978, -12]}
            rotation={[0, 0, 2.828]}
          />
          <mesh
            CastShadow
            geometry={
              nodes[
                "Stock-Light_support-1(07AC0565-8BB1-4B56-90EA-FF6FA2E4FC00)"
              ].geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 1910]}
            rotation={[Math.PI / 2, 1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude2(C0895128-D99F-47E9-9CB2-E68CFBCFE1EC)_1"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2267.68, 73.966, 2516.5]}
            rotation={[Math.PI / 2, 1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Tube(41479441-1032-42DD-BFC0-A0C9141B8F5C)"].geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 20]}
            rotation={[Math.PI / 2, 1.571, 0]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(A64C728B-7C2C-4E6B-AD98-BE4D580358CB)_4"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2534.88, -70.059, -12]}
            rotation={[0, 0, 0.314]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Imported1(622051FF-B5D4-43A5-A9DD-8B44AC266CF9)_6"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2256.68, 73.967, 2270.5]}
            rotation={[-Math.PI / 2, 1.071, Math.PI / 2]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Cut-Extrude2(FF7F0BD6-307C-474E-B4D1-AB875192417B)"]
                .geometry
            }
            material={materials["Paint Matte Black #15"]}
            position={[-2336.68, 73.962, 2440]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <group
            position={[2065.53, 74.125, 0]}
            rotation={[-Math.PI / 2, -1.57, -Math.PI]}
          >
            <group position={[0, 2514, 60.5]}>
              <mesh
                CastShadow
                geometry={
                  nodes["Cut-Extrude22(A951FB75-DAAE-40C6-B308-06544F76DF50)"]
                    .geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(B8A9F8C9-8118-4E18-9234-EE31098DF74C)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(762A2DF7-83F5-4C63-88F7-3B26E260DC73)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(A9964CCE-C56A-4AB6-8A68-3AD2652BA5BA)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(5A91512D-9899-4B52-9FF3-430CF7DDB918)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
            </group>
            <group
              position={[-429.998, 2194.44, -0.1]}
              rotation={[-Math.PI / 2, 0, -0.017]}
            >
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(65AE3EB6-028F-4177-B2AB-B005CE3A71C9)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(3AEC340C-4BDE-4643-A5D8-5589EB4620EE)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(21608849-E3FB-4068-9483-32B4DE0651A5)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(AB91D0B4-CB70-45C7-B8DB-FB21EBE86363)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(B661564F-C50D-45E1-B936-570A835B351A)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(07E5EC1A-A501-43BF-BF52-DD69B5200A33)"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
            </group>
            <group
              position={[429.998, 2194.44, 0.1]}
              rotation={[-Math.PI / 2, 0, 3.124]}
            >
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(65AE3EB6-028F-4177-B2AB-B005CE3A71C9)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(3AEC340C-4BDE-4643-A5D8-5589EB4620EE)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(21608849-E3FB-4068-9483-32B4DE0651A5)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(AB91D0B4-CB70-45C7-B8DB-FB21EBE86363)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(B661564F-C50D-45E1-B936-570A835B351A)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(07E5EC1A-A501-43BF-BF52-DD69B5200A33)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
            </group>
            <group
              position={[0, 2514, -60.5]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                CastShadow
                geometry={
                  nodes["Cut-Extrude22(A951FB75-DAAE-40C6-B308-06544F76DF50)_1"]
                    .geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(B8A9F8C9-8118-4E18-9234-EE31098DF74C)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(762A2DF7-83F5-4C63-88F7-3B26E260DC73)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(A9964CCE-C56A-4AB6-8A68-3AD2652BA5BA)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
              <mesh
                CastShadow
                geometry={
                  nodes["NONE(5A91512D-9899-4B52-9FF3-430CF7DDB918)_1"].geometry
                }
                material={materials["Paint Matte Black #15"]}
              />
            </group>
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(F53245AB-3CBE-4517-9668-5BEB3DB40960)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[144.007, -12, -198.209]}
              rotation={[-Math.PI / 2, 0, -1.317]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2538, -55]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)_1"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2469, 24]}
              rotation={[Math.PI / 2, -0.404, -Math.PI / 2]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)_2"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2469, -24]}
              rotation={[Math.PI / 2, 0.404, Math.PI / 2]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude1(2AB86678-E447-4AF0-A4FE-FDF8BF5E80A2)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["CirPattern1(1D49C864-879F-4045-9E05-043F99978A6A)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude2(BF22995B-261A-4123-AAF5-2BDDFFDA9EF5)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2514, 69]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)_3"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2538, 55]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Tube(CF9BC91A-EAE5-4C98-847C-A678532AB110)"].geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 20, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)_4"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2490, 55]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(F53245AB-3CBE-4517-9668-5BEB3DB40960)_1"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[233.009, -12, 75.709]}
              rotation={[-Math.PI / 2, 0, -2.573]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude2(E844447A-F31D-4C5E-B97E-788433BECAB5)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2437.5, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(39E980E7-C333-4F49-A915-F40982C35B1A)_5"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2490, -55]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(F53245AB-3CBE-4517-9668-5BEB3DB40960)_2"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, -12, 245]}
              rotation={[-Math.PI / 2, 0, 2.453]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(2650FA60-4E38-4234-AACC-94010A355F23)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[-24, 2060, 0]}
              rotation={[-1.049, 0, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(F53245AB-3CBE-4517-9668-5BEB3DB40960)_3"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[-144.007, -12, -198.209]}
              rotation={[-Math.PI / 2, 0, -0.06]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude2(BF22995B-261A-4123-AAF5-2BDDFFDA9EF5)_1"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 2514, -69]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Cut-Extrude3(F53546FB-020B-4077-8C92-5E14421F471D)"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[0, 1959.5, 0]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(F53245AB-3CBE-4517-9668-5BEB3DB40960)_4"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[-233.009, -12, 75.709]}
              rotation={[-Math.PI / 2, 0, 1.196]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(2650FA60-4E38-4234-AACC-94010A355F23)_1"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[24, 145, 0]}
              rotation={[-2.093, 0, -Math.PI]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(2650FA60-4E38-4234-AACC-94010A355F23)_2"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[24, 2060, 0]}
              rotation={[-2.093, 0, -Math.PI]}
            />
            <mesh
              CastShadow
              geometry={
                nodes["Imported1(2650FA60-4E38-4234-AACC-94010A355F23)_3"]
                  .geometry
              }
              material={materials["Paint Matte Black #15"]}
              position={[-24, 145, 0]}
            />
          </group>
          <mesh
            CastShadow
            geometry={
              nodes["Ebene_01(E5E14EEC-A93F-451B-862C-4CE2A98207C6)"].geometry
            }
            material={materials["Plain_Purple_Texture_2768328 - Tri-Planar #1"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["Ebene_01(5B9CE1AD-01A1-4BAA-8FED-0DDD455050D3)"].geometry
            }
            material={materials["Plain_Purple_Texture_2768328 - Tri-Planar #1"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["AUSFORMSCHRAEGEN(9FD2C1B7-65C0-4E5C-8FEB-E0F45E42F6A7)"]
                .geometry
            }
            material={materials["Hard Textured Plastic Black #1"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["AUSFORMSCHRAEGEN(5AFAF1E1-3EAA-4881-9C0E-6B1C0E4AD145)"]
                .geometry
            }
            material={materials["AUSFORMSCHRAEGEN:0:0:0"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["AUSFORMSCHRAEGEN(F3F9C5D7-6C61-445D-925E-35050822753A)"]
                .geometry
            }
            material={materials["AUSFORMSCHRAEGEN:0:0:0"]}
          />
          <mesh
            CastShadow
            geometry={
              nodes["AUSFORMSCHRAEGEN(9654E1AE-7442-4478-AF64-18673D904D59)"]
                .geometry
            }
            material={materials["AUSFORMSCHRAEGEN:0:0:0"]}
          />
        </group>
      </group>
      <OrthographicCamera
        makeDefault={false}
        far={5091.571}
        near={2185.659}
        position={[1.518, 2.745, -4.205]}
        rotation={[-2.553, -0.116, -3.064]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/POLE_01.3.gltf");
