/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ORIANA_FLAVIA_03.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ORIANA_FLAVIA_03.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[1847.439, 0, 0]}>
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_19'].geometry} material={materials['Glass Light Frost White #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_16'].geometry} material={materials['Rubber #2']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_17'].geometry} material={materials['Rubber #2']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_18'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_20'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_21'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_22'].geometry} material={materials['Rubber #2']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_23'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_24'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_25'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_26'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_27'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_28'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_29'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_30'].geometry} material={materials['Paint Textured Red #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_31'].geometry} material={materials['Paint Textured Red #1']} />
        </group>
        <group position={[2695.985, 0, -2630.924]}>
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_35'].geometry} material={materials['Glass Light Frost White #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_32'].geometry} material={materials['Rubber #3']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_33'].geometry} material={materials['Rubber #3']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_34'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_36'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_37'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_38'].geometry} material={materials['Rubber #3']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_39'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_40'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_41'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_42'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_43'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_44'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_45'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_46'].geometry} material={materials['Paint Textured Blue #1']} />
          <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_47'].geometry} material={materials['Paint Textured Blue #1']} />
        </group>
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_1'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_2'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_3'].geometry} material={materials['Glass Light Frost White #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_4'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_5'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_6'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_7'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_8'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_9'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_10'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_11'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_12'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_13'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_14'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_15'].geometry} material={materials['Paint Textured Yellow #1']} />
      </group>
      <PerspectiveCamera makeDefault={false} far={10370.702} near={5906.392} fov={39.598} position={[2.698, 5.644, 5.25]} rotation={[-0.585, 0.254, 0.165]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/ORIANA_FLAVIA_03.gltf')
