/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/matthieu.minguet/Code/ECAL/Projets/ecal-x-ago/src/lights/Upper/UPPER_YELLOW02.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/UPPER_YELLOW02.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_1'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_2'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_3'].geometry} material={materials['Emissive Neutral #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_4'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_5'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_6'].geometry} material={materials['Rubber #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_7'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_8'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_9'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_10'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_11'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_12'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_13'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_14'].geometry} material={materials['Paint Textured Yellow #1']} />
        <mesh geometry={nodes['UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_15'].geometry} material={materials['Paint Textured Yellow #1']} />
      </group>
      <PerspectiveCamera makeDefault={false} far={9688.154} near={4796.897} fov={39.598} position={[-2.363, 2.699, 4.681]} rotation={[-0.36, -0.565, -0.199]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/UPPER_YELLOW02.gltf')
