/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FRAME_01.3.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FRAME_01.3.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[7145.943, 12.882, 167.981]} rotation={[-Math.PI / 2, 0, 0]} scale={0.711}>
          <mesh geometry={nodes['AGO_final_final_final_#2'].geometry} material={materials['Glass Heavy Frost Bright White #1']} />
          <mesh geometry={nodes.AGO_final_final_final_19.geometry} material={materials['Glass Heavy Frost Bright White #1']} position={[-2001.2, 0, 369.7]} scale={0.8} />
          <mesh geometry={nodes['AGO_final_final_final_#3'].geometry} material={materials['Glass Heavy Frost Bright White #1']} />
          <mesh geometry={nodes.AGO_final_final_final_20.geometry} material={materials['Glass Heavy Frost Bright White #1']} position={[-1911.2, 0, 369.7]} scale={0.8} />
          <mesh geometry={nodes.AGO_final_final_final_1.geometry} material={materials['HD Black Packing Foam #1']} />
          <mesh geometry={nodes.AGO_final_final_final_2.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_3.geometry} material={materials['Dark Grey PET 1 #1']} position={[-13.483, 0, 0]} />
          <mesh geometry={nodes.AGO_final_final_final_4.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_5.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_6.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_7.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_8.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_9.geometry} material={materials['Hard Shiny Plastic Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_10.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_11.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_12.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_13.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_14.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_15.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_16.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_17.geometry} material={materials['Paint Matte Black #1']} />
          <mesh geometry={nodes.AGO_final_final_final_18.geometry} material={materials['Glass Heavy Frost Bright White #1']} position={[-2091.2, 0, 369.7]} scale={0.8} />
          <mesh geometry={nodes['AGO_final_final_final_#1'].geometry} material={materials['Glass Heavy Frost Bright White #1']} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={20366.609} near={18486.391} fov={20.408} position={[10.59, 5.869, 15.469]} rotation={[-0.284, 0.562, 0.154]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/FRAME_01.3.gltf')
