/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 JOAB_CHARLOTTE_02.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import EnhancedSpotlight from "../../EnhancedSpotlight";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Planta/JOAB_CHARLOTTE_02.gltf"
  );

  return (
    <group {...props} dispose={null}>
      <group position={[-9.6, 39, 24.1]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={38}
          attenuation={0.7}
          distance={6}
          opacity={1}
          angle={1}
        />
      </group>
      <group scale={0.01}>
        <group position={[1132.62, 1035.436, 4336.4]} scale={10}>
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={0.233}
          >
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_2_2.geometry}
              material={materials.Plastic}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_4_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Tube_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_2_2.geometry}
              material={materials.Matériau_1}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_3_2.geometry}
              material={materials.Matériau_1}
            />
          </group>
          <mesh
            castShadow
            geometry={nodes.BézierCurve001_2.geometry}
            material={materials["black rubber"]}
            position={[-445.228, -98.867, -15.282]}
            rotation={[0, 0.652, 0]}
            scale={232.664}
          />
          <mesh
            castShadow
            geometry={nodes.Soil001_2.geometry}
            material={materials.Soil_1}
            position={[-210.628, -9.863, -189.617]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={288.832}
          />
        </group>
        <group position={[-926.379, -403.526, 2388.681]} scale={75}>
          <mesh
            castShadow
            geometry={nodes.Dirt.geometry}
            material={materials["Burgundy Rubber Plant 2 Dirt"]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            geometry={nodes.Leaf.geometry}
            material={materials["Burgundy Rubber Plant 2 Leaf"]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={20949.014}
        near={11246.499}
        fov={26.991}
        position={[118.454, 65.648, 90.208]}
        rotation={[-0.582, 1.012, 0.539]}
        scale={0.01}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={22774.543}
        near={13072.028}
        fov={26.991}
        position={[133.936, 70.966, 98.288]}
        rotation={[-0.582, 1.012, 0.539]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/JOAB_CHARLOTTE_02.gltf");
