/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 JOAB_CHARLOTTE.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Planta/JOAB_CHARLOTTE.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[1132.62, 1035.436, 4336.4]} scale={10}>
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={0.233}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_lampe_suspendue_2_2.geometry}
              material={materials["Emissive Neutral #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_lampe_suspendue_3_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_pot_2_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_raccord_tube_pot_2_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_raccord_tube_pot_3_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_Feet_d08_2_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_Feet_d08_3_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.AGO_Feet_d08_4_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Tube_2_2.geometry}
              material={materials["Hard Textured Plastic Red #1"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BézierCurve001_2.geometry}
            material={materials["black rubber"]}
            position={[-445.228, -98.867, -15.282]}
            rotation={[0, 0.652, 0]}
            scale={232.664}
          />
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={77.182}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Leaves_2.geometry}
              material={materials.Daun}
              position={[0.144, -0.136, 3.362]}
              rotation={[0, 0, 0.238]}
              scale={3.014}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Soil_2.geometry}
              material={materials.Soil_1}
              position={[-0.002, -0.007, 1.149]}
              scale={4.474}
            />
          </group>
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={22766.49}
        near={13072.028}
        fov={26.991}
        position={[133.936, 70.966, 98.288]}
        rotation={[-0.582, 1.012, 0.539]}
        scale={0.01}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={22766.49}
        near={13072.028}
        fov={26.991}
        position={[133.936, 70.966, 98.288]}
        rotation={[-0.582, 1.012, 0.539]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/JOAB_CHARLOTTE.gltf");
