/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 JOAB_CHARLOTTE_FINAL01.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import EnhancedSpotlight from "../../EnhancedSpotlight";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Planta/JOAB_CHARLOTTE_FINAL01.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[-9.6, 39, 24.1]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={38}
          attenuation={0.7}
          distance={6}
          opacity={1}
          angle={1}
        />
      </group>
      <group scale={0.01}>
        <group position={[1132.62, 1035.436, 4336.4]} scale={10}>
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={0.233}
          >
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_2_2.geometry}
              material={materials["Glass Heavy Frost Bright White #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_4_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Tube_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_2_2.geometry}
              material={materials.Matériau_1}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_3_2.geometry}
              material={materials.Matériau_1}
            />
          </group>
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={77.182}
          >
            <mesh
              castShadow
              geometry={nodes.Leaves_2.geometry}
              material={materials.Daun}
              position={[0.144, -0.136, 3.362]}
              rotation={[0, 0, 0.238]}
              scale={3.014}
            />
            <mesh
              castShadow
              geometry={nodes.Soil_2.geometry}
              material={materials.Soil_1}
              position={[-0.002, -0.007, 1.149]}
              scale={4.474}
            />
          </group>
        </group>
        <mesh
          castShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Soft Rough Black #1"]}
          position={[-934.128, 662.783, 2396.488]}
          scale={[893.676, 536.18, 893.676]}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={20156.174}
        near={10847.166}
        fov={26.991}
        position={[117.714, 40.718, 89.155]}
        rotation={[-0.296, 1.075, 0.291]}
        scale={0.01}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={22766.49}
        near={13072.028}
        fov={26.991}
        position={[133.936, 70.966, 98.288]}
        rotation={[-0.582, 1.012, 0.539]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/JOAB_CHARLOTTE_FINAL01.gltf");
