/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PLANTA_01.3.gltf 
*/

import React from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import EnhancedSpotlight from "../../EnhancedSpotlight";
import { map } from "../../utils/utils";

export function Model(props) {
  const { nodes, materials } = useGLTF("/gltf/Planta/PLANTA_01.3.gltf");
  const dimmingValue = map(props.dimmingValue, 0, 1, 0, 1);

  return (
    <group {...props} dispose={null}>
      <group position={[-3.35, 7, 8.7]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={7}
          attenuation={dimmingValue}
          distance={6}
          opacity={1}
          angle={1}
        />
      </group>
      <group position={[-1.375, 0, 3.911]} scale={0.002}>
        <group position={[1132.62, 1035.436, 4336.4]} scale={10}>
          <group
            position={[-205.9, -98.867, -194.772]}
            rotation={[-Math.PI / 2, 0, 0.652]}
            scale={0.233}
          >
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_2_2.geometry}
              material={materials.Plastic}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_lampe_suspendue_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
              position={[0, 0, 0.393]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_raccord_tube_pot_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_3_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.AGO_Feet_d08_4_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Tube_2_2.geometry}
              material={materials["Paint Textured Red #1"]}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_2_2.geometry}
              material={materials.Matériau_1}
            />
            <mesh
              castShadow
              geometry={nodes.Vis_FH_M8x30_3_2.geometry}
              material={materials.Matériau_1}
            />
          </group>
        </group>
        <group position={[-920.432, -353.738, 2386.204]} scale={67.487}>
          <mesh
            castShadow
            geometry={nodes.Leaf.geometry}
            material={materials["Burgundy Rubber Plant 2 Leaf"]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          geometry={nodes.Disc.geometry}
          material={materials["Hard Rough Plastic Green #1"]}
          position={[-925.472, 926.362, 2391.791]}
          scale={889.929}
        />
      </group>
      <OrthographicCamera
        makeDefault={false}
        far={2660.94}
        near={1711.958}
        position={[16.238, 14.651, 9.831]}
        rotation={[-1.486, 1.096, 1.476]}
        scale={0.01}
      />
      <OrthographicCamera
        makeDefault={false}
        far={2052.12}
        near={1132.88}
        position={[-4.752, 20.521, 9.051]}
        rotation={[-Math.PI / 2, 0, 1.611]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/PLANTA_01.3.gltf");
