/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ORIANA_FLAVIA_04.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import FakeGlowMaterial from "../../FakeGlowMaterial";
import { Sphere } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Upper/ORIANA_FLAVIA_04.gltf"
  );
  const map = (value, x1, y1, x2, y2) =>
    ((value - x1) * (y2 - x2)) / (y1 - x1) + x2;
  const dimmingValue = map(props.dimmingValue, 0, 1, 8, 4);

  return (
    <group {...props} dispose={null}>
      <Sphere args={[1.5, 32, 32]} position={[0, 1.9, 0.01]} renderOrder={1}>
        <FakeGlowMaterial
          falloff={dimmingValue}
          glowInternalRadius={12}
          glowColor={"#fff"}
          opacity={dimmingValue}
          depthTest={false}
        />
      </Sphere>

      <group scale={0.001}>
        <group position={[0, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_35"
              ].geometry
            }
            material={materials["Hard Textured Plastic White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_32"
              ].geometry
            }
            material={materials["Rubber #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_33"
              ].geometry
            }
            material={materials["Rubber #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_34"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_36"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_37"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_38"
              ].geometry
            }
            material={materials["Rubber #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_39"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_40"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_41"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_42"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_43"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_44"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_45"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_46"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_47"
              ].geometry
            }
            material={materials["Paint Textured Blue #1"]}
          />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={10372.385}
        near={5914.451}
        fov={39.598}
        position={[2.68, 5.644, 5.259]}
        rotation={[-0.584, 0.251, 0.163]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/ORIANA_FLAVIA_04.gltf");
