/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ORIANA_FLAVIA_04.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import FakeGlowMaterial from "../../FakeGlowMaterial";
import { Sphere } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Upper/ORIANA_FLAVIA_04.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <Sphere args={[0.4, 32, 32]} position={[0, 1.9, 0.01]} renderOrder={1}>
        <FakeGlowMaterial
          falloff={4}
          glowInternalRadius={10}
          glowColor={"#fff"}
          // glowSharpness={1}
          opacity={0.5}
          toneMapped={true}
          depthTest={true}
        />
      </Sphere>

      <group scale={0.001}>
        <group position={[0, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_19"
              ].geometry
            }
            material={materials["Hard Textured Plastic White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_16"
              ].geometry
            }
            material={materials["Rubber #2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_17"
              ].geometry
            }
            material={materials["Rubber #2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_18"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_20"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_21"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_22"
              ].geometry
            }
            material={materials["Rubber #2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_23"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_24"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_25"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_26"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_27"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_28"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_29"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_30"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_31"
              ].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={10372.385}
        near={5914.451}
        fov={39.598}
        position={[2.68, 5.644, 5.259]}
        rotation={[-0.584, 0.251, 0.163]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/ORIANA_FLAVIA_04.gltf");
