/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ORIANA_FLAVIA_04.gltf 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import FakeGlowMaterial from "../../FakeGlowMaterial";
import { Sphere } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Upper/ORIANA_FLAVIA_04.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <Sphere args={[1.5, 32, 32]} position={[0, 1.9, 0.01]} renderOrder={1}>
        <FakeGlowMaterial
          falloff={4}
          glowInternalRadius={12}
          glowColor={"#fff"}
          opacity={1}
          depthTest={false}
        />
      </Sphere>

      <group scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj"
            ].geometry
          }
          material={materials["Rubber #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_1"
            ].geometry
          }
          material={materials["Rubber #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_2"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_3"
            ].geometry
          }
          material={materials["Hard Textured Plastic White #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_4"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_5"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_6"
            ].geometry
          }
          material={materials["Rubber #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_7"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_8"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_9"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_10"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_11"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_12"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_13"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_14"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes[
              "UserssebaDesktopASSISTANT2023-2024S2AGO_Seoul_HighlightSELECTED_STUDENTS3D_Filesagoorianaflaviaobj_15"
            ].geometry
          }
          material={materials["Paint Textured Yellow #1"]}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={10372.385}
        near={5914.451}
        fov={39.598}
        position={[2.68, 5.644, 5.259]}
        rotation={[-0.584, 0.251, 0.163]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/ORIANA_FLAVIA_04.gltf");
