/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 MAEL_ALEX_04.gltf 
*/

import React from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
} from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/src/lights/Frame/MAEL_ALEX_04.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group
          position={[10054.879, 18.125, 236.362]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_1.geometry}
            material={materials["HD Black Packing Foam #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_2.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_3.geometry}
            material={materials["Dark Grey PET 1 #1"]}
            position={[-13.483, 0, 0]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_4.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_5.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_6.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_7.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_8.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_9.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_10.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_11.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_12.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_13.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_14.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_15.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_16.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_17.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_18.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-2091.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#1_1"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_19.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-2001.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#2"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_20.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-1911.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#3"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
        </group>
        <group
          position={[10054.879, 18.125, 236.362]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_21.geometry}
            material={materials["HD Black Packing Foam #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_22.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_23.geometry}
            material={materials["Dark Grey PET 1 #1"]}
            position={[-13.483, 0, 0]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_24.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_25.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_26.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_27.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_28.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_29.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_30.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_31.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_32.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_33.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_34.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_35.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_36.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_37.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_38.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-2091.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#1_2"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_39.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-2001.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#2_1"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_40.geometry}
            material={materials["Emissive Warm #1"]}
            position={[-1911.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#3_1"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
        </group>
      </group>
      <OrthographicCamera
        makeDefault={false}
        far={4805.009}
        near={0.001}
        position={[1.157, 1.477, 1.081]}
        rotation={[-0.576, 0.86, 0.439]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={5645.144}
        near={2000.754}
        fov={39.598}
        position={[0.05, 0.981, 5]}
        rotation={[-0.005, 0, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6517.592}
        near={816.117}
        fov={39.598}
        position={[-4.234, 1.065, 3.019]}
        rotation={[-0.009, -0.96, -0.007]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={7783.78}
        near={2159.443}
        fov={39.598}
        position={[3.376, 1.065, 3.955]}
        rotation={[-0.007, 0.698, 0.004]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={3468.354}
        near={0.001}
        fov={39.598}
        position={[-1.859, 1.772, 1.253]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={4139.765}
        near={506.102}
        fov={39.598}
        position={[0.046, 1.876, 3.5]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6153.96}
        near={1751.12}
        fov={39.598}
        position={[-5, 1.001, 0.236]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={5983.817}
        near={368.893}
        fov={95.97}
        position={[2.429, 0.607, 2.676]}
        rotation={[0.112, 0.573, -0.078]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6692.627}
        near={1077.703}
        fov={95.97}
        position={[2.806, 0.848, 3.307]}
        rotation={[0.112, 0.573, -0.078]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={4653.96}
        near={251.12}
        fov={20.408}
        position={[-3.5, 1.804, 0.237]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/MAEL_ALEX_04.gltf");
