/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 MAEL_ALEXANDRE_FINAL.gltf 
*/
import EnhancedSpotlight from "../../EnhancedSpotlight";

import React from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
} from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/src/lights/Frame/MAEL_ALEXANDRE_FINAL.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[0.05, 0.86, 0.23]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={0.8}
          attenuation={3}
          distance={30}
          opacity={0.4}
          angle={3}
        />
      </group>
      <group position={[0.49, 0.86, 0.23]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={0.8}
          attenuation={3}
          distance={30}
          opacity={0.4}
          angle={3}
        />
      </group>
      <group position={[-0.4, 0.86, 0.23]}>
        <EnhancedSpotlight
          position={[0, 1, 0]}
          castShadow={false}
          scale={0.8}
          attenuation={3}
          distance={30}
          opacity={0.4}
          angle={3}
        />
      </group>

      <group scale={0.001}>
        <group
          position={[10054.879, 18.125, 236.362]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_4.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_5.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_6.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_7.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_8.geometry}
            material={materials["Hard Shiny Plastic Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_9.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_10.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_11.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_12.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_13.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_14.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_15.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_16.geometry}
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_17.geometry}
            material={materials["Clear Rough Plastic White #2"]}
            position={[-2091.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#1_#1"].geometry}
            material={materials["Clear Rough Plastic White #2"]}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#1_1"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_18.geometry}
            material={materials["Clear Rough Plastic White #2"]}
            position={[-2001.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#2"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
          <mesh
            castShadow
            geometry={nodes.AGO_final_final_final_19.geometry}
            material={materials["Clear Rough Plastic White #2"]}
            position={[-1911.2, 0, 369.7]}
            scale={0.8}
          />
          <mesh
            castShadow
            geometry={nodes["AGO_final_final_final_#3"].geometry}
            material={materials["Clear Rough Plastic White #1"]}
          />
        </group>
      </group>
      <OrthographicCamera
        makeDefault={false}
        far={3138.181}
        near={116.947}
        position={[1.157, 1.477, 1.081]}
        rotation={[-0.576, 0.86, 0.439]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={5645.144}
        near={4354.856}
        fov={39.598}
        position={[0.05, 0.981, 5]}
        rotation={[-0.005, 0, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6431.517}
        near={3968.483}
        fov={39.598}
        position={[-4.234, 1.065, 3.019]}
        rotation={[-0.009, -0.96, -0.007]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6369.667}
        near={4030.333}
        fov={39.598}
        position={[3.376, 1.065, 3.955]}
        rotation={[-0.007, 0.698, 0.004]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={3394.051}
        near={1005.949}
        fov={39.598}
        position={[-1.859, 1.772, 1.253]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={4139.765}
        near={2860.235}
        fov={39.598}
        position={[0.046, 1.876, 3.5]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={6048.879}
        near={3951.121}
        fov={39.598}
        position={[-5, 1.001, 0.236]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={4790.929}
        near={2391.45}
        fov={95.97}
        position={[2.429, 0.607, 2.676]}
        rotation={[0.112, 0.573, -0.078]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={5499.739}
        near={3100.261}
        fov={95.97}
        position={[2.806, 0.848, 3.307]}
        rotation={[0.112, 0.573, -0.078]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={4548.879}
        near={2451.121}
        fov={20.408}
        position={[-3.5, 1.804, 0.237]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/MAEL_ALEXANDRE_FINAL.gltf");
